import argparse
from common import utils

def parse_encoder(parser, arg_str=None):
    enc_parser = parser.add_argument_group()
    #utils.parse_optimizer(parser)

    enc_parser.add_argument('--conv_type', type=str,
                        help='type of convolution')
    enc_parser.add_argument('--method_type', type=str,
                        help='type of embedding')
    enc_parser.add_argument('--batch_size', type=int,
                        help='Training batch size')
    enc_parser.add_argument('--n_layers', type=int,
                        help='Number of graph conv layers')
    enc_parser.add_argument('--hidden_dim', type=int,
                        help='Training hidden size')
    enc_parser.add_argument('--skip', type=str,
                        help='"all" or "last"')
    enc_parser.add_argument('--dropout', type=float,
                        help='Dropout rate')
    enc_parser.add_argument('--n_batches', type=int,
                        help='Number of training minibatches')
    enc_parser.add_argument('--margin', type=float,
                        help='margin for loss')
    enc_parser.add_argument('--dataset', type=str,
                        help='Dataset')
    enc_parser.add_argument('--test_set', type=str,
                        help='test set filename')
    enc_parser.add_argument('--eval_interval', type=int,
                        help='how often to eval during training')
    enc_parser.add_argument('--val_size', type=int,
                        help='validation set size')
    enc_parser.add_argument('--model_path', type=str,
                        help='path to save/load model')
    enc_parser.add_argument('--opt_scheduler', type=str,
                        help='scheduler name')
    enc_parser.add_argument('--node_anchored', action="store_true",
                        help='whether to use node anchoring in training')
    enc_parser.add_argument('--test', action="store_true")
    enc_parser.add_argument('--n_workers', type=int)
    enc_parser.add_argument('--tag', type=str,
        help='tag to identify the run')
    enc_parser.add_argument("--graph_pkl_path", type=str, default=None,
                    help="Path to the .pkl file containing the graph to be used for training")
    enc_parser.add_argument('--semantic_preset', type=str,
                    help='Semantic synthetic preset: biology, ecommerce, or social')
    enc_parser.add_argument('--semantic_mix_presets', type=str,
                    help='Comma-separated presets for mixed training, e.g. biology,ecommerce,social')
    enc_parser.add_argument('--semantic_mix_weights', type=str,
                    help='Comma-separated weights for semantic_mix_presets, e.g. 0.4,0.4,0.2')
    enc_parser.add_argument('--val_semantic_preset', type=str,
                    help='Optional heldout semantic preset for validation/test generation')
    enc_parser.add_argument('--label_neg_ratio', type=float,
                    help='Fraction of negatives that are label-corruption negatives')
    enc_parser.add_argument('--hard_negative_ratio', type=float,
                    help='Fraction of structural negatives sampled as harder near-miss negatives')
    enc_parser.add_argument('--label_noise', type=float,
                    help='Label corruption rate during semantic synthetic generation')
    enc_parser.add_argument('--use_label_features', action="store_true",
                    help='Augment node features with label_id buckets')
    enc_parser.add_argument('--label_feature_dim', type=int,
                    help='One-hot dimension for label_id feature buckets')
    enc_parser.add_argument('--semantic_mode', type=str,
                    help='Semantic feature mode: categorical or hybrid_text')
    enc_parser.add_argument('--label_encoder_backend', type=str,
                    help='Frozen label encoder backend: auto, sentence_transformers, cache_only, or hashing')
    enc_parser.add_argument('--label_encoder_name', type=str,
                    help='Frozen text encoder model name when using hybrid_text mode')
    enc_parser.add_argument('--label_encoder_cache_dir', type=str,
                    help='Optional cache directory for frozen label embeddings')
    enc_parser.add_argument('--text_encoder_dim', type=int,
                    help='Raw frozen label embedding dimension before projection')
    enc_parser.add_argument('--text_label_dim', type=int,
                    help='Projected text-label feature dimension added to node features')
    enc_parser.add_argument('--seed', type=int,
                    help='Global random seed')
    enc_parser.add_argument('--order_threshold_mode', type=str,
                    help='Prediction mode for order model: clf or margin')
    enc_parser.add_argument('--order_margin_factor', type=float,
                    help='When threshold_mode=margin, classify as positive if score <= margin*factor')
    enc_parser.add_argument('--encoder_type', type=str,
                    help='Graph encoder: baseline or rgcn_basis')
    enc_parser.add_argument('--num_relations', type=int,
                    help='Maximum number of supported edge relation ids (including UNK/overflow)')
    enc_parser.add_argument('--num_bases', type=int,
                    help='Number of basis matrices for rgcn_basis encoder')
    enc_parser.add_argument('--rel_reg_lambda', type=float,
                    help='Regularization strength for relation coefficients in rgcn_basis encoder')

    enc_parser.set_defaults(conv_type='SAGE',
                        method_type='order',
                        dataset='syn',
                        n_layers=8,
                        batch_size=16,
                        hidden_dim=64,
                        skip="learnable",
                        dropout=0.0,
                        n_batches=10000,
                        opt='adam',   # opt_enc_parser
                        opt_scheduler='none',
                        opt_restart=100,
                        weight_decay=0.0,
                        lr=1e-4,
                        margin=0.1,
                        test_set='',
                        eval_interval=1000,
                        n_workers=4,
                        model_path="ckpt/model.pt",
                        tag='',
                        val_size=128,
                        node_anchored=True,
                        semantic_preset='biology',
                        semantic_mix_presets='biology,ecommerce,social',
                        semantic_mix_weights='0.34,0.33,0.33',
                        val_semantic_preset='',
                        label_neg_ratio=0.5,
                        hard_negative_ratio=0.5,
                        label_noise=0.05,
                        use_label_features=False,
                        label_feature_dim=16,
                        semantic_mode='categorical',
                        label_encoder_backend='auto',
                        label_encoder_name='sentence-transformers/all-MiniLM-L6-v2',
                        label_encoder_cache_dir='artifacts/label_encoder_cache',
                        text_encoder_dim=384,
                        text_label_dim=64,
                        seed=42,
                        order_threshold_mode='clf',
                        order_margin_factor=0.5,
                        encoder_type='baseline',
                        num_relations=64,
                        num_bases=8,
                        rel_reg_lambda=1e-4)

    #return enc_parser.parse_args(arg_str)

